spring:
  application:
    name: matappen
  datasource:
    url: jdbc:mysql://localhost:3306/matappen
    username: root
    password: password
  mvc:
    contentnegotiation:
      media-types:
        wasm: application/wasm
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
upload:
  path: path
---
spring:
  config:
    activate:
      on-profile: dev
upload:
  path: ${UPLOAD_PATH}

